#!/usr/bin/env zsh

local bookmark_name="$1"
local exact_bookmark; exact_bookmark=$(grep -E "\|${bookmark_name}$" "$BOOKMARKS_FILE" 2>/dev/null)

if [[ -n "${exact_bookmark}" ]] ; then
  local dir="${exact_bookmark%%|*}"
  builtin cd ${dir//\~/$HOME}
else
  local aprox_bookmark; aprox_bookmark=$(grep -E "\|.*${bookmark_name}.*$" "$BOOKMARKS_FILE" 2>/dev/null)
  if [[ -z "${aprox_bookmark}" ]] ; then
    echo "No bookmark with name ${bookmark_name} found!"
    echo 'Available bookmarks :'
    marks
    echo "\nIn order to create marked folders 'cd' into the folder and use 'mark' or 'mark foo'"
    return 1
  fi
  MATCHING_MARK_COUNT=$(echo "$aprox_bookmark" | wc -l)
  if (( $MATCHING_MARK_COUNT > 1 )) ; then
    echo "More than one bookmark matches your query '$bookmark_name'"
    echo "Matching bookmarks ($MATCHING_MARK_COUNT) : "
    echo "${aprox_bookmark}" | cut -d'|' -f2 |  paste -sd"," -
    return 1
  fi
  local dir="${aprox_bookmark%%|*}"
  builtin cd ${dir//\~/$HOME}
fi
