#!/usr/bin/env zsh

local bookmark_name=$1

if [[ -z $bookmark_name ]]; then
  bookmark_name="${PWD:t}"
fi

# Is root dir?
if [[ -z $bookmark_name ]]; then
  bookmark_name='/'
fi

local p="$(print -nD $PWD)"

if ! awk -F'|' -v p="$p" '$1 == p {found=1; exit} END {exit !found}' "$ZPM_BOOKMARKS_FILE"; then
  # Store the bookmark as folder|name
  echo "${p}|${bookmark_name}" >> "$ZPM_BOOKMARKS_FILE"
  echo "Bookmark '${bookmark_name}' saved"
  return 0
fi

echo 'Bookmark already exists'
return 1
