#!/usr/bin/env zsh

local bookmark_file="$(<"$ZPM_BOOKMARKS_FILE")"
local bookmark_path
local bookmark_name

if [[ -n "$1" ]]; then
  @bookmark_path_colorize "$(awk -F'|' -v n="$1" '$2 == n {print $1}' <<< "$bookmark_file")"
  echo
else
  local -a names paths
  local -i max_len=0
  local line
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    bookmark_path="${line%|*}"
    bookmark_name="${line#*|}"

    if [[ -n "$bookmark_path" && -n "$bookmark_name" ]]; then
      names+=("$bookmark_name")
      paths+=("$bookmark_path")
      (( ${#bookmark_name} > max_len )) && max_len=${#bookmark_name}
    fi
  done <<< "$bookmark_file"

  for i in {1..${#names}}; do
    local c_name="$(@bookmark_name_colorize "${names[i]}")"
    local c_path="$(@bookmark_path_colorize "${paths[i]}")"
    local -i pad=$(( max_len - ${#names[i]} ))
    local spaces=""
    (( pad > 0 )) && spaces="${(l:pad:: :)}"
    printf "%s%s  %s--%s %s\n" "$c_name" "$spaces" "${c[yellow]}${c[bold]}" "${c[reset]}" "$c_path"
  done
fi
